//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasualHeroes.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.RequestTags = new HashSet<RequestTag>();
            this.UserTags = new HashSet<UserTag>();
        }
    
        public long TagId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RequestTag> RequestTags { get; set; }
        public virtual ICollection<UserTag> UserTags { get; set; }
    }
}
