//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasualHeroes.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Requests = new HashSet<Request>();
            this.UserTags = new HashSet<UserTag>();
            this.AcceptedRequests = new HashSet<AcceptedRequest>();
        }
    
        public long UserId { get; set; }
        public string Identifier { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Tags { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> CreatedOn { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<UserTag> UserTags { get; set; }
        public virtual ICollection<AcceptedRequest> AcceptedRequests { get; set; }
    }
}
